blog/urls.py
from django.urls import path
from . import views

app_name='blog'

urlpatterns = [
    path('', views.blog, name='blog'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

portfolio_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    date = models.DateField()

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

# Create your models here.

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from .models import Blog

# Create your views here.
def blog(request):
    blogs = Blog.objects.order_by('-date')
    return render(request, 'blog/blog.html',{
        'blogs':blogs,
    })

def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {
        'id':blog
    })

portfolio/views.py
from django.shortcuts import render
from .models import Project

# Create your views here.
def home(request):
    projects = Project.objects.all()

    return render(request,'portfolio/home.html',{
        'projects':projects
    })

blog/templates/blog/blog.html
{% extends 'portfolio/base.html' %}

{% block content %}
<h1 class="font-weight-bold text-center">Blog</h1>

<p>I have {{ blogs.count }} blog{{ blogs.count|pluralize }}</p>

{% for blog in blogs %}
    <div class="row justify-content-center my-3">
        <div class="col-md-10">
            <a href="{% url 'blog:detail' blog.id %}"><h3>{{ blog.title }}</h3></a>
            <p>{{ blog.date|date:'M d Y'|upper }}</p>
            <p>{{ blog.description|striptags|truncatechars:100 }}</p>
        </div>
    </div>
{% endfor %}
{% endblock %}

blog/templates/blog/detail.html
{% extends 'portfolio/base.html' %}

{% block content %}
<h1 class="text-center mt-5">{{ id.title }}</h1>

<h4 class="text-center text-muted mb-5">{{ id.date|date:'F j Y' }}</h4>

<p class="mt-5"></p>{{ id.description|safe }}
{% endblock %}

portfolio/templates/portfolio/base.html
{% load static %}

<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
  <link rel="icon" type="image/png" href="{% static 'portfolio/icon.png' %}">

  <title>Jerwin's Portfolio</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static 'portfolio/icon.png' %}" width="30" height="30" class="d-inline-block align-top"  alt="Logo">
        <span>Home</span>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% static 'portfolio/inforgraphic.pdf' %}">Inforgraphic</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://www.linkedin.com/in/jerwin-carreon-7b6751201/" target="_blank">LinkedIn</a>
          </li>
          <li class="nav-item">
            <a role="button" class="btn btn-primary" href="{% url 'blog:blog' %}" target="_blank">Blog</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
{% block content %}
{% endblock content%}
</body>
</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}
{% load static %}

{% block content %}
<div class="row justify-content-center my-3">
    <div class="col-5">
        <img src="{% static 'portfolio/car.jpg' %}" class="img-fluid">
    </div>
</div>

<div class="row justify-content-center mb-3">
    <div class="col-md-9 text-center">
        <h1 class="font-weight-bold">Jerwin's Portfolio</h1>
    </div>
</div>
<hr>
<h2 class="mt-5">Portfolio</h2>
<div class="row">
    {% for project in projects %}
    <div class="col-lg-4 col-md-6">
        {% if project.url %}
            <br>
            <a href="{{ project.url }}">link
            <img src="{{ project.image.url }}" class="img-fluid mb-2">
            </a>
        {% else %}
            <img src="{{ project.image.url }}" class="img-fluid mb-2">
        {% endif %}
        <h2>{{ project.title }}</h2>
        <p>{{ project.description }}</p>
    </div>
    {% endfor %}
</div>
{% endblock %}